baseURL = 'http://pasank.com/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "anatole"

[params]
title = "Pasan Karunaratne"
author = "Pasan Karunaratne"
description = "My machine learning musings"
profilePicture = "images/profile-pic-sea.jpeg"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/pasanOnline"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/pasankarunaratne/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:pasankarunaratne@gmail.com"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/pasank"

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

